### ISSUE TITLE
Amiga Mouse automatic moves to border

### ISSUE THREAD

**Issue by kangoroo82** [351ELEC/351ELEC#712]
In uae the mouse curser moves automatic to the border.

**Comment by YonKuma** [comment]
@kangoroo82 What device (P/M/V/MP) are you using, and what version of the OS (stable or beta and if beta what release)?

**Comment by kangoroo82** [comment]
351v and beta-20211111_2216

**Comment by YonKuma** [comment]
Thanks. I'll look into it

**Comment by kangoroo82** [comment]
thanks for your work, but the mouse curser always moves from the top of the bottom of the screen, till it reaches the boarder.

**Comment by YonKuma** [comment]
@kangoroo82 You're using the latest release? Are you using puae as your emulator, or are you using a non-default emulator? Is there any chance you have overrides in place that are overwriting the setting?

If you get the chance, please open up the RA quick menu, go to Options > Input > Mouse Controller Deadzone (or something, don't remember the exact name), and check that it's being set to 25% rather than 20%

**Comment by kangoroo82** [comment]
ok. now it's great. thank you. i changed it manually. i thought with the latest beta it is done. but it wasn't changed. many thanks. please put that in the next beta.
